version: '2'

networks:
  topcoder-review:

services:
  ca-base:
    image: hyperledger/fabric-ca
    command: /bin/bash -c '/scripts/start-ca.sh'
    environment:
      - FABRIC_CA_SERVER_HOME=/etc/hyperledger/fabric-ca
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_DEBUG=true
      - BOOTSTRAP_USER_PASS=admin:adminpw
    volumes:
      - ../fabric-ca/scripts:/scripts
      - ../fabric-ca/config:/etc/hyperledger/fabric-ca/config
    networks:
      - topcoder-review