# Copyright (c) 2018 TopCoder, Inc. All rights reserved.
#
# author: TCSDEVELOPER
# version: 1.0

version: '2'

volumes:
  orderer.topcoder.com:
  peer0.topcoder.topcoder.com:
  peer1.topcoder.topcoder.com:
  peer0.clients.topcoder.com:
  peer1.clients.topcoder.com:
  peer0.members.topcoder.com:
  peer1.members.topcoder.com:
  peer0.moderators.topcoder.com:
  peer1.moderators.topcoder.com:

networks:
  topcoder-review:

services:

  orderer.topcoder.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.topcoder.com
    container_name: orderer.topcoder.com
    networks:
      - topcoder-review

  peer0.topcoder.topcoder.com:
    container_name: peer0.topcoder.topcoder.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.topcoder.topcoder.com
    networks:
      - topcoder-review

  peer1.topcoder.topcoder.com:
    container_name: peer1.topcoder.topcoder.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.topcoder.topcoder.com
    networks:
      - topcoder-review

  peer0.clients.topcoder.com:
    container_name: peer0.clients.topcoder.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.clients.topcoder.com
    networks:
      - topcoder-review

  peer1.clients.topcoder.com:
    container_name: peer1.clients.topcoder.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.clients.topcoder.com
    networks:
      - topcoder-review

  peer0.members.topcoder.com:
    container_name: peer0.members.topcoder.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.members.topcoder.com
    networks:
      - topcoder-review

  peer1.members.topcoder.com:
    container_name: peer1.members.topcoder.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.members.topcoder.com
    networks:
      - topcoder-review

  peer0.moderators.topcoder.com:
    container_name: peer0.moderators.topcoder.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.moderators.topcoder.com
    networks:
      - topcoder-review

  peer1.moderators.topcoder.com:
    container_name: peer1.moderators.topcoder.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.moderators.topcoder.com
    networks:
      - topcoder-review

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.topcoder.topcoder.com:7051
      - CORE_PEER_LOCALMSPID=TopcoderMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/topcoder.topcoder.com/peers/peer0.topcoder.topcoder.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/topcoder.topcoder.com/peers/peer0.topcoder.topcoder.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/topcoder.topcoder.com/peers/peer0.topcoder.topcoder.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/topcoder.topcoder.com/users/Admin@topcoder.topcoder.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./tests:/opt/gopath/src/github.com/hyperledger/fabric/peer/tests/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.topcoder.com
      - peer0.topcoder.topcoder.com
      - peer1.topcoder.topcoder.com
      - peer0.clients.topcoder.com
      - peer1.clients.topcoder.com
      - peer0.members.topcoder.com
      - peer1.members.topcoder.com
      - peer0.moderators.topcoder.com
      - peer1.moderators.topcoder.com
    networks:
      - topcoder-review

  ipfs-node:
    container_name: ipfs-node
    image: jbenet/go-ipfs:latest
    tty: true
    stdin_open: true
    volumes:
      - ./ipfs_data/export:/export
      - ./ipfs_data/data:/data/ipfs
    ports:
      - 8080:8080
      - 4001:4001
      - 5001:5001
    networks:
      - topcoder-review
